// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDANikxdBqQIJ3g14rY6wIinJHvZ7Zpc9A',
//     appId: '1:558571535305:web:c78a5eedd9b4e4543cc618',
//     messagingSenderId: '558571535305',
//     projectId: 'stockflow-1f243',
//     authDomain: 'stockflow-1f243.firebaseapp.com',
//     storageBucket: 'stockflow-1f243.firebasestorage.app',
//     measurementId: 'G-RZVLK51BFD',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyC30WPmVbZWOU36AgKvsaYxHd3MA02CQsg',
//     appId: '1:558571535305:android:8d8c3cf2ab1fbb773cc618',
//     messagingSenderId: '558571535305',
//     projectId: 'stockflow-1f243',
//     storageBucket: 'stockflow-1f243.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCu8F7eIEEg5J7Ie_kYLwkI4bsb4i12oys',
//     appId: '1:558571535305:ios:a3cdaa107eaa42bb3cc618',
//     messagingSenderId: '558571535305',
//     projectId: 'stockflow-1f243',
//     storageBucket: 'stockflow-1f243.firebasestorage.app',
//     iosBundleId: 'com.example.stockflow',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCu8F7eIEEg5J7Ie_kYLwkI4bsb4i12oys',
//     appId: '1:558571535305:ios:a3cdaa107eaa42bb3cc618',
//     messagingSenderId: '558571535305',
//     projectId: 'stockflow-1f243',
//     storageBucket: 'stockflow-1f243.firebasestorage.app',
//     iosBundleId: 'com.example.stockflow',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDANikxdBqQIJ3g14rY6wIinJHvZ7Zpc9A',
//     appId: '1:558571535305:web:ccd66174522a47873cc618',
//     messagingSenderId: '558571535305',
//     projectId: 'stockflow-1f243',
//     authDomain: 'stockflow-1f243.firebaseapp.com',
//     storageBucket: 'stockflow-1f243.firebasestorage.app',
//     measurementId: 'G-BZTJK7QF21',
//   );
// }
